export const LOGIN_REQUEST = 'USERS_LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'USERS_LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'USERS_LOGIN_FAILURE';

export const LOGOUT = 'USERS_LOGOUT';

export const REGISTER_REQUEST = 'USERS_REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'USERS_REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'USERS_REGISTER_FAILURE';

export const FORGOT_PASSWORD_REQUEST = 'USERS_FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'USERS_FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'USERS_FORGOT_PASSWORD_FAILURE';

export const RESET_PASSWORD_REQUEST = 'USERS_RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'USERS_RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'USERS_RESET_PASSWORD_FAILURE';

